### PR TITLE
Catch and process errors that occure during annotation instantiation

### LINKED ISSUE #437: Catch TypeError during annotation instantiation and throw a more meaningful AnnotationException
I ran into this error:

```
In OneToMany.php line 45:

  [TypeError]
  Argument 3 passed to Doctrine\ORM\Mapping\OneToMany::__construct() must be of the type array or null,
  string given, called in vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 971

Exception trace:
  at vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/OneToMany.php:45
 Doctrine\ORM\Mapping\OneToMany->__construct() at vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:971
 Doctrine\Common\Annotations\DocParser->Annotation() at vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:719
 Doctrine\Common\Annotations\DocParser->Annotations() at vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:376
 Doctrine\Common\Annotations\DocParser->parse() at vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php:178
 Doctrine\Common\Annotations\AnnotationReader->getPropertyAnnotations() at vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/PsrCachedReader.php:155
```

I traced calls and variables back to a `@OneToMany` annotation on a property of an entity containing a misconfiguration and fixed it:

```diff
     /**
      * @var Collection<int, Page>|null
-     * @ORM\OneToMany(targetEntity="App\Entity\Page", mappedBy="user", cascade="persist")
+     * @ORM\OneToMany(targetEntity="App\Entity\Page", mappedBy="user", cascade={"persist"})
      */
    private ?Collection $pages;
```

It's not clear from the error neither the trace (coming from a query being executed and objects being hydrated) on which entity and which property this occurred.

I looked into `\Doctrine\Common\Annotations\DocParser` and there are many checks being done and many places where there might be a `\Doctrine\Common\Annotations\AnnotationException` being thrown with clear messages.

Should we catch `TypeError`s upon the annotation instantiation [here](https://github.com/doctrine/annotations/blob/1.13.x/lib/Doctrine/Common/Annotations/DocParser.php#L944) and [here](https://github.com/doctrine/annotations/blob/1.13.x/lib/Doctrine/Common/Annotations/DocParser.php#L971) and throw an `AnnotationException` with a proper message containing the annotation and property on which it occurred?

### PR DESCRIPTION
**Pull request by 7ochem**
When an annotation class is instantiated and values are passed to the constructor, TypeErrors and ArgumentCountErrors can be thrown. This change catches those exceptions and shows an AnnotationException containing the annotation name and context.

Resolves: #437

### CODE REVIEW

File: lib/Doctrine/Common/Annotations/DocParser.php [hunk 1]
```diff
@@ -1456,4 +1458,102 @@ private function resolvePositionalValues(array $arguments, string $name): array
...
+     * @param array<string,mixed>|null $arguments
+     *
+     * @return object
+     *
+     * @throws AnnotationException
+     */
+    private function instantiateAnnotiation(string $originalName, string $context, string $name, ?array $arguments = null)
+    {
+        try {
+            if ($arguments === null) {
```
Comment (stof) [inline lib/Doctrine/Common/Annotations/DocParser.php]: couldn't you use an empty array as default value and then always use `return new $name(...$arguments);` ?

File: lib/Doctrine/Common/Annotations/DocParser.php [hunk 2]
```diff
@@ -1456,4 +1458,102 @@ private function resolvePositionalValues(array $arguments, string $name): array
...
+
+            return new $name(...$arguments);
+        } catch (ArgumentCountError $argumentCountError) {
+            $matchCount = preg_match(
+                '/^Too few arguments to function (.*?)::__construct\(\), (\d+) passed in .*? on line \d+ and (at least|exactly) (\d+) expected/',
+                $argumentCountError->getMessage(),
+                $matches
+            );
+            if ($matchCount === 1 && $matches[1] === $name) {
+                throw AnnotationException::creationError(sprintf(
```
Comment (stof) [inline lib/Doctrine/Common/Annotations/DocParser.php]: Can we attach the caught error as previous exception ?

File: lib/Doctrine/Common/Annotations/DocParser.php [hunk 3]
```diff
@@ -1456,4 +1458,102 @@ private function resolvePositionalValues(array $arguments, string $name): array
...
+expects "%s" to be declared.
+EXCEPTION
+                    ,
+                    $originalName,
+                    $context,
+                    $matches[2]
+                ));
+            }
+
+            // ArgumentCountError is not in the expected form or was not caused by the call to the `$name` constructor, so re-throw.
```
Comment (stof) [inline lib/Doctrine/Common/Annotations/DocParser.php]: Well, the exception happened during the instantiation. So I would still always provide the context of which annotation was instantiated, to allow debugging it.
Attaching the original error as previous throwable means we can support it for any error (Saying something like `Instantiating the annotation @%s declared on %s failed.`)

Comment (stof) [reply lib/Doctrine/Common/Annotations/DocParser.php]: and this would remove the need to try matching PHP error messages (which are not covered by BC rules AFAIK)

**Review by stof — CHANGES_REQUESTED** [review]
This should have tests

File: lib/Doctrine/Common/Annotations/DocParser.php (hunk 3 above)
Comment (7ochem) [reply lib/Doctrine/Common/Annotations/DocParser.php]: Good point. While working on this, it all started to be a bit bloated. So this would indeed be a better solution.

**Comment by 7ochem** [comment]
> This should have tests

Thanks Christophe for the super fast feedback and valid points 🙏🏻 I'll work on it a bit more

**Comment by 7ochem** [comment]
I changed the code and made it catch all `\Throwable` when instantiating the annotation class. This meant that I had to update some existing tests that were testing for an `\InvalidArgumentException` thrown in the constructor of the annotation. The advantage is that these exceptions are now also provided with the context and target.

File: lib/Doctrine/Common/Annotations/DocParser.php [hunk 4]
```diff
@@ -1456,4 +1457,31 @@ private function resolvePositionalValues(array $arguments, string $name): array
...
+     * @return object
+     *
+     * @throws AnnotationException
+     */
+    private function instantiateAnnotiation(string $originalName, string $context, string $name, array $arguments)
+    {
+        try {
+            return new $name(...$arguments);
+        } catch (Throwable $exception) {
+            throw AnnotationException::creationError(
```
Comment (7ochem) [inline lib/Doctrine/Common/Annotations/DocParser.php:1476]: Maybe... I should add here:
```php
if ($exception instanceof AnnotationException) {
    throw $exception;
}
```

Because annotations have annotations themself. And if an exception happens in those, then you get that exception, wrapped up in an AnnotationException and that will be wrapped up in an AnnotationException (and can go on...).

Comment (stof) [reply lib/Doctrine/Common/Annotations/DocParser.php:1476]: instantiating a class will not read its doctrine annotations

File: tests/Doctrine/Tests/Common/Annotations/DocParserTest.php [hunk 5]
```diff
@@ -897,9 +909,20 @@ public function testAnnotationEnumInvalidLiteralDeclarationException(): void
...
         $parser->setIgnoreNotImportedAnnotations(false);
-        $this->expectException(InvalidArgumentException::class);
-        $this->expectExceptionMessage('Undefined enumerator value "3" for literal "AnnotationEnumLiteral::THREE".');
-        $parser->parse($docblock);
+        $this->expectException(AnnotationException::class);
+        try {
+            $parser->parse($docblock);
+        } catch (AnnotationException $exc) {
+            $previous = $exc->getPrevious();
+            $this->assertNotEmpty($previous);
```
Comment (stof) [inline tests/Doctrine/Tests/Common/Annotations/DocParserTest.php]: can be removed. The `assertInstanceOf` will already reject `null`

File: lib/Doctrine/Common/Annotations/DocParser.php (hunk 4 above)
Comment (7ochem) [reply lib/Doctrine/Common/Annotations/DocParser.php:1476]: That's true

File: phpstan.neon [hunk 6]
```diff
@@ -13,6 +13,7 @@ parameters:
     ignoreErrors:
         - '#Instantiated class Doctrine_Tests_Common_Annotations_Fixtures_ClassNoNamespaceNoComment not found#'
         - '#Property Doctrine\\Tests\\Common\\Annotations\\DummyClassNonAnnotationProblem::\$foo has unknown class#'
+        - '#Call to an undefined static method PHPUnit\\Framework\\TestCase::expectExceptionMessageRegExp\(\)#'
```
Comment (7ochem) [inline phpstan.neon:16]: Here https://github.com/doctrine/annotations/blob/065fad5dd716558d954075bbc32093cec55594e2/tests/Doctrine/Tests/Common/Annotations/DocParserTest.php#L1752-L1756

Either one of those exists: `expectExceptionMessageRegExp` exists in PHPUnit 7, deprecated in 8 and removed in 9 (and thus PHPStan gives an error). `expectExceptionMessageMatches` exists in PHPUnit 8 and up

**Review by malarzm — APPROVED** [review]

**Comment by malarzm** [comment]
Thanks @7ochem for the improvement and sorry for the long merge time!

**Comment by 7ochem** [comment]
> Thanks @7ochem for the improvement and sorry for the long merge time!

Thanks for merging! And no problem 👍🏻
